Update geojson file (using `@fused.cache`) (#964)
When calling a file on a cloud directory / hosted somewhere I did end up
getting

```
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

My guess is because I did too many calls in a few seconds when
iterating, so adding `@fused.cache` should prevent this from happening